
<Downloader>:
    orientation: 'vertical'
    Label:
        text: 'Para baixar automaticamente seus recibos da DCTF WEB;\nSiga as seguintes instrunções:'
        halign: 'center'

    BoxLayout:
        spacing: 20
        padding: 20
        Button:
            text: 'Iniciar'

        BoxLayout:
            spacing: 10
            orientation: 'vertical'
            Button:
                text: 'Voltar'

            Button:
                text: 'Pular'